<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_stylesheet_directory() . '/includes/hooks.php' );
require ( get_stylesheet_directory() . '/includes/functions.php' );

