<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */

// theme classes etc.
require ( get_stylesheet_directory() . '/lib/legambiente/eu-cookie-control/eu-cookie-control.php');

// hooks and theme-specific logic etc.
require ( get_stylesheet_directory() . '/includes/hooks.php' );
require ( get_stylesheet_directory() . '/includes/utils.php' );
require ( get_stylesheet_directory() . '/includes/admin-menu-permissions.php' );
require ( get_stylesheet_directory() . '/includes/functions.php' );
require ( get_stylesheet_directory() . '/includes/taxonomies.php' );
require ( get_stylesheet_directory() . '/includes/widgets.php' );
